backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)
# publish_mode: editorial_workflow
media_folder: "/media/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "services"
    label: "Services"
    folder: "services"
    create: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    sortable_fields: ['date', 'title']
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["service"] }
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Short Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Content", name: "content", widget: "markdown", required: false}
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}" # Filename template, e.g., YYYY-MM-DD-title.md
    sortable_fields: ['commit_date', 'title']
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["service"] }
      - { label: "Heading", name: "heading", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Content", name: "content", widget: "markdown" }